job('First-Maven-Project-Via-DSL') {
    description("First Maven Job Generated By the DSL on ${new Date()}, the Project is a Small Maven Project Hosted On GitHub")
    scm {
        git("git@github.com:ashokdesai3290/Jenkins_Demo.git", 'main')
    }
    triggers {
        scm('* * * * *')
    }
    steps {
        maven('clean package', 'maven-samples/single-module/pom.xml')
    }
    publishers {
        //archive the war file generated
        archiveArtifacts '**/*.jar'
    }
}